---
schema-version: '1.0'
name: OpenSearch
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v2
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: index-management
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: anomaly-detection
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: asynchronous-search
    integ-test:
      test-configs:
        - with-security
        - without-security
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: alerting
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: notifications
    working-directory: notifications
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: sql
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: k-NN
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: dashboards-reports
    working-directory: reports-scheduler
    bwc-test:
      test-configs:
        - without-security

  - name: opensearch-observability
    working-directory: opensearch-observability
    bwc-test:
      test-configs:
        - without-security

  - name: ml-commons
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: cross-cluster-replication
    bwc-test:
      test-configs:
        - with-security
        - without-security

  - name: security
    bwc-test:
      test-configs:
        - with-security

  - name: geospatial
    bwc-test:
      test-configs:
        - without-security
